name: Build DEB Package

on:
  push:
    branches:
      - main  # 当推送到main分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dpkg-dev fakeroot

      - name: Prepare DEB build script
        run: |
          # 在这里编写你的构建脚本，或者将现有的脚本复制到工作目录中
          cat <<EOL > build-deb.sh
          #!/bin/bash

          # 设置项目名称和版本号
          PROJECT_NAME="your-project-name"
          VERSION="1.0.0"

          # 创建debian目录并添加必要的文件
          mkdir -p debian
          cat <<INNER_EOL > debian/control
          Package: \${PROJECT_NAME}
          Version: \${VERSION}
          Section: base
          Priority: optional
          Architecture: all
          Depends: 
          Maintainer: Your Name <your-email@example.com>
          Description: A brief description of your project
           .
           Your project description here.
          INNER_EOL

          # 这里可以添加其他必要的debian文件（如rules、changelog等）的构建逻辑
          # ...

          # 构建deb文件
          dpkg-buildpackage -us -uc
          EOL
          chmod +x build-deb.sh

      - name: Build DEB package
        run: |
          ./build-deb.sh

      - name: Upload DEB package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: q19507550
          path: BreadcrumbsInject-IPA/.github/workflows
